export function reset(s){return "\x1b[0m"+s+"\x1b[0m"}
export function bright(s){return "\x1b[1m"+s+"\x1b[0m"}
export function dim(s){return "\x1b[2m"+s+"\x1b[0m"}
export function underscore(s){return "\x1b[4m"+s+"\x1b[0m"}
export function blink(s){return "\x1b[5m"+s+"\x1b[0m"}
export function reverse(s){return "\x1b[7m"+s+"\x1b[0m"}
export function hidden(s){return "\x1b[8m"+s+"\x1b[0m"}
export function black(s){return "\x1b[30m"+s+"\x1b[0m"}
export function red(s){return "\x1b[31m"+s+"\x1b[0m"}
export function green(s){return "\x1b[32m"+s+"\x1b[0m"}
export function yellow(s){return "\x1b[33m"+s+"\x1b[0m"}
export function blue(s){return "\x1b[34m"+s+"\x1b[0m"}
export function magenta(s){return "\x1b[35m"+s+"\x1b[0m"}
export function cyan(s){return "\x1b[36m"+s+"\x1b[0m"}
export function white(s){return "\x1b[37m"+s+"\x1b[0m"}
export function crimson(s){return "\x1b[38m"+s+"\x1b[0m"}
export function bgblack(s){return "\x1b[40m"+s+"\x1b[0m"}
export function bgred(s){return "\x1b[41m"+s+"\x1b[0m"}
export function bggreen(s){return "\x1b[42m"+s+"\x1b[0m"}
export function bgyellow(s){return "\x1b[43m"+s+"\x1b[0m"}
export function bgblue(s){return "\x1b[44m"+s+"\x1b[0m"}
export function bgmagenta(s){return "\x1b[45m"+s+"\x1b[0m"}
export function bgcyan(s){return "\x1b[46m"+s+"\x1b[0m"}
export function bgwhite(s){return "\x1b[47m"+s+"\x1b[0m"}
export function bgcrimson(s){return "\x1b[48m"+s+"\x1b[0m"}
